### ISSUE TITLE
"Last Commit" tab not working.

### ISSUE THREAD

**Issue by puresyntax71** [stackbit/jamstackthemes#223]
Navigating to https://jamstackthemes.dev/#ssg=gatsby and clicking on "Last Commit" produces this error:

> homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:144 Uncaught TypeError: attrA.toLowerCase is not a function
>     at mixitup.Mixer.compare (homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:144)
>     at homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:142
>     at Array.sort (<anonymous>)
>     at mixitup.Mixer.sortOperation (homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:142)
>     at mixitup.Mixer.getOperation (homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:302)
>     at mixitup.Mixer.multimix (homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:296)
>     at mixitup.Control.handleClick (homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:81)
>     at HTMLDocument.self.handler (homeBundle.min.68cf540628598023fedf4b8282d691e35fddb910d381cb9c8c6f3c2f599f1ef0.js:73)

**Comment by JugglerX** [comment]
@puresyntax71 thanks for the report. this issue has been fixed
