### ISSUE TITLE
The "Theme Info" button is broken on demo page

### ISSUE THREAD

**Issue by iaeiou** [stackbit/jamstackthemes#273]
Hi,

## "Show me the bug"

Allright:

- browse any theme demo page. For example https://jamstackthemes.dev/demo/theme/bilberry-hugo-theme/
- in the top-right corner, click on "Theme info"

You should be redirected to the very same page, i.e the same demo page

## Expected behavior

The link should point to the theme details. For Bilberry, this is https://jamstackthemes.dev/theme/bilberry-hugo-theme/

**Comment by JugglerX** [comment]
@iaeiou thank you for the bug report. This issue should be fixed now.

**Comment by iaeiou** [comment]
> This issue should be fixed now.

Yes it is, thanks!

**Comment by apvarun** [comment]
@JugglerX I see the page to be broken for a lot more themes ( 3 out of first 10 in homepage )
https://jamstackthemes.dev/demo/theme/hugo-digital-garden/
https://jamstackthemes.dev/demo/theme/urban/
https://jamstackthemes.dev/demo/theme/tradly/

**Comment by iaeiou** [comment]
Hi @apvarun,
thanks for the report!
You should open a dedicated issue though, to avoid these notes to get lost

**Comment by iaeiou** [comment]
>  You should open a dedicated issue though, to avoid these notes to get lost

Dedicated report done here: https://github.com/stackbit/jamstackthemes/issues/286
