### ISSUE TITLE
Asking explanation .

### ISSUE THREAD

**Issue by mehedi-sharif** [stackbit/jamstackthemes#293]
Please clarify why did you mentioned this line in your readme .
 "We also advise you not to purchase products from the following companies: Themefisher and Gethugothemes. " 
Can you legally do that ? If yes, in which ground ? In which terms do you think Themefisher and Gethugothemes did something unethical ?
I need a proper explanation . 
Thanks

**Comment by tfsomrat** [comment]
We’ve taken down statichunt.com 
Currently, we don’t have any plan with Statichunt. If we do anything in the future we’ll not use your codebase anymore. 
Hope you can now remove the text from your README.md file. And we hope you will include our themes to jamstackthemes.dev website which you removed, Thanks.

@JugglerX

**Comment by JugglerX** [comment]
@tfsomrat @mehedi-sharif 

Thank you for doing the right thing.
