### ISSUE TITLE
Need help for getting access to 2 themes that were removed recently

### ISSUE THREAD

**Issue by ishaan-puniani** [stackbit/jamstackthemes#331]
Hello, 

I need help to get access/zip or fork for the themes that were removed recently as a part of  https://github.com/stackbit/jamstackthemes/commit/85cbfd172d9b490e057d34153d0b4dbc1c9a0d16#diff-b88c2ab0ca8f928c08975a99dd8a1dc8d90327c965351a90673ad4ac64e962e6

1) content/theme/stackbit-app-nextjs.md
2) content/theme/stackbit-personal-nextjs.md

Would be great help, Thanks !!

**Comment by ishaan-puniani** [comment]
Hello @TomasBankauskas ,
Can you please help with this request. 

--
Thanks
Ishaan

**Comment by TomasBankauskas** [comment]
Hi @ishaan-puniani sorry for long reply. I have responded you via email.
