### ISSUE TITLE
there is no new related data in theme.json

### ISSUE THREAD

**Issue by leslieyin** [stackbit/jamstackthemes#349]
hi，When I add a new theme, the image is generated in the static directory, but the relevant data is not added in themes.json

Is it a problem with build.js configuration?

please help take a look ，thanks a lot！

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by leslieyin** [comment]
Resolved

**Comment by RoneoOrg** [comment]
Could you please share your solution @leslieyin?
Thanks!
