### ISSUE TITLE
Build a Hugo Theme Based on This

### ISSUE THREAD

**Issue by SamGreenwood1** [stackbit/jamstackthemes#454]
I downloaded this repo a year and a bit ago, thinking it was a theme, not realizing it was the entire site. I was trying to use it to create a program bank for my summer camp. However, I couldn't reverse engineer it well enough to determine what I needed to change to fit my requirements.

**Comment by TomasBankauskas** [comment]
@SamGreenwood1 Hi there. Yes, jamstackthemes repo is a site dedicated to showcase free open source themes built with various tools. You need to pick one of the themes from [the site](https://jamstackthemes.dev/) and try to modify to suit your needs.
